os:
  - linux
  - osx

language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      - xvfb

install:
  - npm ci

script:
  - npm run lint
  - npm run citest

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '10'
      install: skip
      script: echo "Deploying to npm ..."
      after_script: skip
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: toJBfxH1H5KuIvpO/W2uxMmRfjSD2J+RMjLuYwZJ2E1DY8dsKacY8UEkNECzbWMaqDThVuMOtZvbbYalnV7sLsISyUPRRnsHnk8+QRqdXKLBCIiOUCwm7/GDyWt8poKU1S4HWEOlaCZzStAJSRpv5ftq3OZtX+7AT2ZtDs2YOQNS4olbi1ApwFaZ+KWPbFIpt7YgrwdEth4z9ICTSpNgCUUl44gexHWarqVu7kwFsswVROfnQltEiOpQ26lEtMzKph52fBluADJPy+iXSoPNCqftdAdYr63Sqb5KsBzq8dFCnQKHFFmLcNPoA8+U1tGK3gQtJTGD0+0nzMAlFRwhm1lLjLesSC3scYVC+9pybXziXoqiRciEsGlmvMDHUKHbTiXjSo22oJxkuLSFRBEePOu7QqJkcyqb1Elo3kyb7g4tYvKCW9mGyc31m9Z3cjwLT5EfbHW48zDyylRC4iXLq5VCkNz5e2T+JGG8lFRh8dvWR2ZjkTb/yNDMfPCaxEpjeCBUnWBiz8ddRUUOOWEoUXRAMQVDLxsSzNJBJGN0ATvMtmoTmTEL0GSKQS+6WkbMEFxc8vH9744BTbLyYi7lB3MoNRP15dgaGF3xfwPUwxwAiWO3zEY5XG4WMhBVFFQ48NyLlRUDWHz1USvbeNkHCXQhHQOZbQaVa7B0H7/zIuQ=
        on:
          tags: true
          repo: catdad/electronmon
