os:
  - linux
  - osx

language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      - xvfb

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=':99.0'                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & ; fi
  - npm ci

script:
  - npm run lint
  - npm test
