name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  FORCE_COLOR: 1

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]
        electron: [11]
        include:
          - node: 12
            os: ubuntu-latest
            electron: 10
          - node: 12
            os: macos-latest
            electron: 9
          - node: 10
            os: windows-latest
            electron: 8
          - node: 10
            os: macos-latest
            electron: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install xvfb
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install electron@${{ matrix.electron }}
      - run: node --version
      - run: npx electron --version
      - name: npm test
        run: npx xvfb-maybe npm test
